module SkelT where

-- Haskell module generated by the BNF converter

import AbsT
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transTree :: Tree -> Result
transTree x = case x of
  ETree integer string tree1 tree2 -> failure x
  EmptyTree -> failure x

