module SkelT where

-- Haskell module generated by the BNF converter

import AbsT
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transVector :: Vector -> Result
transVector x = case x of
  EVect double1 double2 -> failure x

